

services:
  server:
    build: .
    container_name: backend
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./server:/app
      - server_data:/data
    depends_on:
      - mongo

  client:
    build: ./client
    container_name: frontend
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - server
    restart: unless-stopped
    volumes:
      - ./client:/app

  # Uncomment the following if you want to use Nginx as a reverse proxy
  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - server
  #     - client

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  server_data:
  mongo-data: 