version: '3.8'

services:
  server:
    build: ./server
    container_name: backend
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/ecommerce
    restart: unless-stopped
    volumes:
      - ./server:/app

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=ecommerce
    volumes:
      - mongo_data:/data/db

  # Uncomment the following if you have a React frontend in ./client
  # client:
  #   build: ./client
  #   container_name: frontend
  #   env_file:
  #     - .env
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - server
  #   restart: unless-stopped
  #   volumes:
  #     - ./client:/app

  # Uncomment the following if you want to use Nginx as a reverse proxy
  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - server
  #     - client

volumes:
  mongo_data: 